---
title: "Clase_miercoles"
author: "Andrea Monzalvo"
date: "24/2/2021"
output: html_document
---
#Summarized Experiment 

renglones -> genes
columnas -> samples

```{r}
## Lets build our first SummarizedExperiment object
library("SummarizedExperiment")
## ?SummarizedExperiment
## De los ejemplos en la ayuda oficial
## Creamos los datos para nuestro objeto de tipo SummarizedExperiment
## para 200 genes a lo largo de 6 muestras
nrows <- 200
ncols <- 6
## Números al azar de cuentas
set.seed(20210223)
counts <- matrix(runif(nrows * ncols, 1, 1e4), nrows)
## Información de nuestros genes
rowRanges <- GRanges(
    rep(c("chr1", "chr2"), c(50, 150)),
    IRanges(floor(runif(200, 1e5, 1e6)), width = 100),
    strand = sample(c("+", "-"), 200, TRUE),
    feature_id = sprintf("ID%03d", 1:200)
)
names(rowRanges) <- paste0("gene_", seq_len(length(rowRanges)))
## Información de nuestras muestras
colData <- DataFrame(
    Treatment = rep(c("ChIP", "Input"), 3),
    row.names = LETTERS[1:6]
)
## Juntamos ahora toda la información en un solo objeto de R
rse <- SummarizedExperiment(
    assays = SimpleList(counts = counts),
    rowRanges = rowRanges,
    colData = colData
)
## Exploremos el objeto resultante
rse
```

### Extraer alguna información

```{r}
#tabla assay
head(assay(rse))
```
```{r}
#ver los cromosomas
seqlevels(rse)

## Tabla comprimida por repetición de cada level (chromosoma)
seqnames(rowRanges(rse))

#Imprimir tabla counts
assay(rse, 'counts')

```

### Ejercicio en clase

```{r}
#Ejercicio
## Comando 1
rse[1:2, ]
head(assay(rse[1:2, ]))
```
Como los renglones corresponden a los genes, aqui nos muestra un sub-set con sólo los primeros 2 genes.

```{r}
## Comando 2
rse[, c("A", "D", "F")]
head(assay(rse[, c("A", "D", "F")]))
```
Como las columnas son features, aquí accesamos a un subset con las primeras tres features.


# recount3

```{r}
## Load recount3 R package
library("recount3")


## Revisemos todos los proyectos con datos de humano en recount3
human_projects <- available_projects()


## Encuentra tu proyecto de interés. Aquí usaremos
## SRP009615 de ejemplo
proj_info <- subset(
    human_projects,
    project == "SRP009615" & project_type == "data_sources"
)
## Crea un objeto de tipo RangedSummarizedExperiment (RSE)
## con la información a nivel de genes
rse_gene_SRP009615 <- create_rse(proj_info)

## Explora el objeto RSE
rse_gene_SRP009615
```

### Forma interactiva

```{r}
## Explora los proyectos disponibles de forma interactiva
proj_info_interactive <- interactiveDisplayBase::display(human_projects)
## Selecciona un solo renglón en la tabla y da click en "send".

## Aquí verificamos que solo seleccionaste un solo renglón.
stopifnot(nrow(proj_info_interactive) == 1)
## Crea el objeto RSE
rse_gene_interactive <- create_rse(proj_info_interactive)
```

### Hacer counts

```{r}
## Convirtamos las cuentas por nucleotido a cuentas por lectura
## usando compute_read_counts().
## Para otras transformaciones como RPKM y TPM, revisa transform_counts().
assay(rse_gene_SRP009615, "counts") <- compute_read_counts(rse_gene_SRP009615)
```

```{r}
## Para este estudio en específico, hagamos más fácil de usar la
## información del experimento
rse_gene_SRP009615 <- expand_sra_attributes(rse_gene_SRP009615)
colData(rse_gene_SRP009615)[
    ,
    grepl("^sra_attribute", colnames(colData(rse_gene_SRP009615)))
]
```

### Usar iSSE

```{r}
## Explora el objeto rse de forma interactiva
library("iSEE")
iSEE::iSEE(rse_gene_SRP009615)
```


